### ISSUE TITLE
老哥你写得好复杂啊。

### ISSUE THREAD

**Issue by cheetah747** [qihuan92/PhotoWidget#4]
我看半天愣是没找到你跳转选取图片是怎么走的。。。

**Comment by qihuan92** [comment]
感谢关注😄
针对于配置页面确实还需要进一步的优化，目前那块耦合度比较高，无奈近期时间不够😂
选取图片用的是 Result API，具体的跳转到系统的图片选择器是这一行：
https://github.com/qihuan92/PhotoWidget/blob/79fead25881f8db857fcae874d819bd5ef2cc2c2/app/src/main/java/com/qihuan/photowidget/config/BaseConfigureActivity.kt#L350
